name: Auto Live TV Playlist Ultimate Update

on:
  schedule:
    - cron: '0 * * * *' # প্রতি ১ ঘণ্টা পর পর (ঘণ্টার শুরুতে) অটো রান হবে
  workflow_dispatch: # যখন খুশি ম্যানুয়ালি রান করার অপশন

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install requests pytz

      - name: Run Ultimate Scraper
        run: python merge_script.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add playlist.m3u
          # যদি কোনো পরিবর্তন না থাকে তবে এরর ছাড়াই শেষ হবে
          git commit -m "Hourly Ultimate Update: $(date)" || exit 0
          git push
          
